version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    command:
      - mysqld
      - "--explicit_defaults_for_timestamp=true"
      - "--default-time-zone=-03:00"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
